### ISSUE TITLE
setting charset di db_connector

### ISSUE THREAD

**Issue by piantgrunger** [fastplaz/fastplaz#284]
saat databaseinit() tidak bisa mengisi property charset di db_connector jadi saat data saya di db berupa unicode di output yang di tampilkan jadi "?????"
mungkin bisa ditambahkan pengisian charset di saat databaseinit dari config.json

**Comment by luridarmawan** [comment]
nice idea ...
thanks you

**Comment by luridarmawan** [comment]
@piantgrunger 

done.
update sudah dimasukkan ke branch development, silakan dipull.

di file config.json bisa ditambahkan field 'charset', formatnya:

```
  "database" : {
    "default" : {
      "driver" : "MySQL 5.7",
      "hostname" : "localhost",
      "port" : "",
      "username" : "your_username",
      "password" : "your_password",
      "database_name" : "your_database",
      "charset" : "",
      "prefix" : "",
      "library" : ""
    }
  },

```

**Comment by luridarmawan** [comment]
ref:
[merge request #285 ](https://github.com/fastplaz/fastplaz/pull/285)

**Comment by piantgrunger** [comment]
Makasih om ..
