### ISSUE TITLE
saat build dari folder carik dengan menggunakan build.sh ada error carik_webmodule.pas(16,22) Fatal: Can't find unit jobplanet_integration used by carik_webmodule 

### ISSUE THREAD

**Issue by piantgrunger** [fastplaz/fastplaz#338]
saat build dari folder carik dengan menggunakan build.sh ada error carik_webmodule.pas(16,22) Fatal: Can't find unit jobplanet_integration used by carik_webmodule kelihatannya belum di add kan source integration tersebut

**Comment by luridarmawan** [comment]
@piantgrunger pastikan masing2 menggunakan branch yang sama.
Carik dengan branch development, fastplaz jg dari branch development.
sy kroscek jg
